### ISSUE TITLE
USB Webcam not working for OctoPrint on Windows

### ISSUE THREAD

**Issue by Afalti** [jneilliii/OctoPrint-WindowsInstaller#10]
Hi! I am currently running the OctoPrint for Windows, and I am trying to use a USB webcam, and remember having to go through a process to do the same on the pi version, do I have to do the same thing, or is there a different process to get the webcam working for the windows version?

**Comment by jneilliii** [comment]
During the install there was an option to install YawCam. If that option was enabled then it will be running as a service in the background (again if that option was enabled at the end of the install process). The only caveat to that is if you didn't have java installed during the setup process YawCam install probably failed. Check your start menu to see if you have a YawCam entry. If not, you'll probably have to go through manually installing that yourself.

**Comment by JMVS** [comment]
Maybe I'm going a little off-topic here, but what about [cam2web](https://github.com/cvsandbox/cam2web)? I've been using it for at least a year now and seems to be working great. It does not need JRE and can be compiled for 32 & 64 bits.

**Comment by jneilliii** [comment]
If it works, by all means use it and thanks for the pointer. I will investigate to see if it's possible to integrate as option maybe.

**Comment by Afalti** [comment]
Thank you for all of your suggestions, I will try them out once I am back at my PC. If you find anything, please let me know.

**Comment by Afalti** [comment]
I have successfully installed YawCam, but cant seem to connect it to octoprint, any tips on how to do this?

**Comment by Afalti** [comment]
Thank you all for your help, I have successfully installed and set up yawcam with my instance of octoprint, after finding the ending required for the IP by searching through the code, once again, thank you all.
