### ISSUE TITLE
Windows 22H2 Build 19045.3393

### ISSUE THREAD

**Issue by Afalti** [jneilliii/OctoPrint-WindowsInstaller#15]
I just updated to the most recent version of Windows 22H2, and OctoPrint is no longer launching, I believe it is one of the recent updates, and was wondering if anyone else encountered this problem or if anyone has a solution other than completely starting the computer over from scratch.

**Comment by Afalti** [comment]
I have checked the firewall settings, tried the new installer, tried doing a erase and restore and restore a backup manually, ive even tried turning it off and back on again.

**Comment by jneilliii** [comment]
Can you share your octoprint.log from c:\OctoPrint\basedir\5000\ and the OctoPrintService5000.wrapper.log file from C:\OctoPrint\ please?

**Comment by Afalti** [comment]
i can once I get back to my computer, but when I looked at it the latest log was from july, and it didnt report any errors. I will probably be able to get those to you tomorrow morning

**Comment by Afalti** [comment]
[OctoPrintService5000.wrapper.log](https://github.com/jneilliii/OctoPrint-WindowsInstaller/files/12497421/OctoPrintService5000.wrapper.log)

**Comment by Afalti** [comment]
I cant attach octoprint.log since it is too big

**Comment by Afalti** [comment]
what do you need from the octoprint.log?

**Comment by jneilliii** [comment]
if it's that big then you probably have an issue with a plugin acting up filling the log file. Go into windows service manager, stop the OctoPrint on Port 5000 service, delete the log file and then start the service back up and let's try to get a clean startup and minimal log entries.

**Comment by jneilliii** [comment]
the wrapper log seems to indicate the service keeps trying to start over and over, so definitely seems like octoprint itself is experiencing issues starting.

**Comment by Afalti** [comment]
I have stopped the service, deleted octoprint.log and started the service, and am currently waiting a few minutes for it to start up, and I will see what results that gives me

**Comment by Afalti** [comment]
after about 3 and a half minutes the log hit 1,092 kb, and I stopped the service because it still wouldnt open on a browser, but even after stopping it, it kept getting bigger

**Comment by Afalti** [comment]
I managed to stop octoprint.log from increasing in size by changing the startup style from automatic to manual

**Comment by Afalti** [comment]
[octoprint.log](https://github.com/jneilliii/OctoPrint-WindowsInstaller/files/12500322/octoprint.log)
this is the new octoprint.log that was running while the service was "active" for 3 and a half minutes, and then while "inactive" for 4 minutes

**Comment by jneilliii** [comment]
Ok, looks like an older version of of the installer and you probably tried to upgrade OctoPrint at some point and it has corrupted the install. I've since added an upgrade script to the latest installer. In order to get around this here is what you will have to do. 

1. Stop the OctoPrint service completely
2. Move the 5000 folder from C:\OctoPrint\basedir\ to your desktop
3. Uninstall OctoPrint from Windows Settings > Apps
4. Delete the C:\OctoPrint\ folder
5. Install the latest release
6. Stop the service again before setting up anything
7. Move the 5000 folder back to C:\OctoPrint\basedir
8. Start the service

I hope that works.

**Comment by jneilliii** [comment]
one step missed...

Open Registry editor after uninstall and delete the entry for 5000 in HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\OctoPrint\Instances

**Comment by Afalti** [comment]
looking at the registry editor after uninstall, and I am in the OctoPrint directory, but not finding the instances subdirectory

**Comment by Afalti** [comment]
I followed the steps and it is working now, thank you for the help!

**Comment by jneilliii** [comment]
> looking at the registry editor after uninstall, and I am in the OctoPrint directory, but not finding the instances subdirectory

wasn't sure if the uninstaller would remove that registry value or not. 

> I followed the steps and it is working now, thank you for the help!

great news, glad we were able to get it sorted. 

moving forward, when you get an update notice for OctoPrint don't try to do it from the web interface, instead use the Upgrade OctoPrint shortcut added to the start menu under the OctoPrint folder.
