### ISSUE TITLE
Creality K1 max

### ISSUE THREAD

**Issue by medium2spirit** [jneilliii/OctoPrint-WindowsInstaller#18]
Hi I am new to 3D printing and have been trying to get Octo Print to work with my Creality K1 Max but don't think there is support for it yet. Is this correct? if so is it possible to add support for it?

**Comment by jneilliii** [comment]
Unfortunately I don't think the k1 is compatible with any host software. 

https://community.octoprint.org/t/trying-to-develop-a-way-to-connect-to-the-creality-k1-board/53475?u=jneilliii

https://community.octoprint.org/t/will-octoprint-interface-and-work-with-a-creality-k1/53182?u=jneilliii

Either way, nothing to do with the windows installer project here, but more creality firmware question.

**Comment by medium2spirit** [comment]
OK thanks for your quick response

Regards Stephen Robinson
________________________________
