### ISSUE TITLE
Can't install plugin

### ISSUE THREAD

**Issue by SqualeDev** [jneilliii/OctoPrint-WindowsInstaller#20]
I've tried to install filamentManager plugin on my OctoPrint installed on Windows with the plugin manager without success. 

[octoprint-systeminfo-20231118162657.zip](https://github.com/jneilliii/OctoPrint-WindowsInstaller/files/13400713/octoprint-systeminfo-20231118162657.zip)

How can I do this ?
Thanks a lot for your response

**Comment by jneilliii** [comment]
It seems to have installed perfectly fine. 
> 2023-11-18 15:53:48,842 > Successfully installed OctoPrint-FilamentManager-1.9.1

but you are getting an error on load, which is a plugin problem not a windows installer problem.
> 2023-11-18 15:51:50,439 - octoprint.plugin.core - ERROR - Error loading plugin filamentmanager

**Comment by jneilliii** [comment]
seems there is an issue posted already similar.

https://github.com/OllisGit/OctoPrint-FilamentManager/issues/23

**Comment by jneilliii** [comment]
you might be able to copy/paste this URL into plugin manager > get more > ...from URL (at the bottom of the dialog) and click install.

```
https://github.com/bitsy-ai/OctoPrint-FilamentManager/archive/refs/heads/fix-python-10-compat.zip
```
