### ISSUE TITLE
Plugin Files

### ISSUE THREAD

**Issue by Afalti** [jneilliii/OctoPrint-WindowsInstaller#24]
I am trying to find the plugin files for octoprint on windows, but I can not seem to find them anywhere, does anyone know where I can find them?

**Comment by jneilliii** [comment]
What do you mean plugin files?

**Comment by Afalti** [comment]
if I am looking for the code for plugins, like their base code for python, javascript, CSS, things like that, to look at to get a feel for how they work, where would I find those files.

**Comment by jneilliii** [comment]
Oh, it's usually easier to just to look at the plugin source code on GitHub, but to answer the question, when plugins get installed they end up landing into a sub-folder in the path C:\OctoPrint\WPy64-31050\python-3.10.5.amd64\Lib\site-packages\
