### ISSUE TITLE
Installed the 1.10.0 but still 1.9.3?

### ISSUE THREAD

**Issue by cylstudio** [jneilliii/OctoPrint-WindowsInstaller#29]
Hi there, I have installed the 1.10.0 to my windows but not sure why is it still showing 1.9.3?  I have two instances, not sure if that's the reason? thanks

**Comment by jneilliii** [comment]
That's odd. If you already had OctoPrint installed and are just trying to upgrade you should use the start menu of windows and under OctoPrint folder there is an Upgrade option. Do this while not printing on either instance. I took a quick look at the installer and it did build with OctoPrint 1.10.0, but will double-check when I have some time.

**Comment by jneilliii** [comment]
I can confirm that the latest 1.10.0 installer does in fact install OctoPrint 1.10.0, so recommend you looking at the upgrade option I mentioned in the previous reply.
