### ISSUE TITLE
Malware detection by VirusTotal

### ISSUE THREAD

**Issue by DaveInCaz** [jneilliii/OctoPrint-WindowsInstaller#30]
I downloaded the file `OctoPrint.Setup.1.10.2.exe` from https://github.com/jneilliii/OctoPrint-WindowsInstaller/releases/tag/1.10.2 and checked it with [VirusTotal](https://www.virustotal.com/gui/file/c6a8a30648af162a9b6d7711ba20880ff3c446e993efd3cd71cc3c5a65208ba9). It reported one malware detection:

![image](https://github.com/user-attachments/assets/f5ac5759-5f13-41a1-83d4-77f398028b7a)

I don't know if this is a false positive or what (it was the only one out of 70 to show a positive detection) but it seems like a concern.

Thanks

**Comment by jneilliii** [comment]
Well, all the source of the files are available here and in the corresponding repositories of other tools used to build the installer. You can choose to use it or not, that's your choice, but I have no reason to install or push anything malicious.
